### ISSUE TITLE
Safewalk

### ISSUE THREAD

**Issue by Jacktherippa** [KurtisAD/NoVa-SRC#28]
Should be easy enough. Perhaps specification of certain thresholds of height could be walked off of and it not affect the hack? For example, doing -safewalk .0125 would allow you to walk off a threshold if the distance between the block beneath your feet and the one adjacent (where you're trying to step) is about .0125 lower than the current block. I believe this would allow one to walk down snow layers that are stacked on top of one another.

**Comment by KurtisAD** [comment]
The current safewalk implementation is just treating every action as if you're sneaking. The tolerance may be possible depending how sneaking is implemented
