### ISSUE TITLE
Schematica

### ISSUE THREAD

**Issue by Jacktherippa** [KurtisAD/NoVa-SRC#37]
Visualization for building. Can load schematics and display needed materials. 

I'm probably asking too much on this one.

**Comment by KurtisAD** [comment]
This can be done with dorq's psuedo server client. This would require a lot of work, but it's not impossible. Not a priority

**Comment by KurtisAD** [comment]
I also dont think this is in scope

**Comment by Jacktherippa** [comment]
That's cool. I just wanted the idea to be put out there should the ability to make it possible come true.

**Comment by gtavbeastaya** [comment]
It'd indeed be cool when you are building something on 2b2t that you had in creative

**Comment by KurtisAD** [comment]
Except it's not in scope, and there is another tool that I mentioned that fulfills the role
