### ISSUE TITLE
Notifications errors keep poping up in chat

### ISSUE THREAD

**Issue by Jacktherippa** [KurtisAD/NoVa-SRC#58]
A constant stream of "You have to provide arguments for this command" will trickle into the chat upon activation of notifications.

This cannot be turned off, even when notifications are disabled.

EDIT: this is the log off event that isn't fully fixed yet. the log in and last seen location bits work as intended though. Please fix.

**Comment by KurtisAD** [comment]
Steps to reproduce?

**Comment by Jacktherippa** [comment]
I just enabled notifications and it started coming up
disabling things like see, loc, and log don't seem to affect it. 

The messages are unpredictable.

**Comment by Jacktherippa** [comment]
Never mind, it was a mis-bound key.
Problem solved.
